image: node:latest

stages:
-install
-test
-build
-deploy

install:
  stage: install
  script:
    - npm install
  artifacts:
   expire_in: 2d
   paths:
   -node_modules/
  cache:
   paths:
   -node_modules

test:
  stage: 
  variables:
   CHROME_BIN: google-chrome
  dependencies:
   -install
  before_script:
   - apt-get update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
   npm run test:ci
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/' 